services:
  wordpress:
    image: docker.io/wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./html:/var/www/html # Garde ce volume pour un contrôle total
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Augmentation des uploads
    networks:
      - wp_network

  db:
    image: docker.io/mariadb:10.5
    container_name: mariadb-wordpress
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - wp_network

networks:
  wp_network:
    driver: bridge
